const notFoundError = (res) => {
    return res.status(404).send('Dado n√£o encontrado.');
};

module.exports = {
    notFoundError,
};
